#+title: Readme

* Get related with the project
** Who is tiacloudinfo?
The docker file pull the image from this user in Docker Hub https://hub.docker.com/u/tiacloudinfo

Looking into the commit history and bits of the code there is an email and domain related to Francis "francis.poku@tiacloud.io" probably this lab project started there.

Nice photo Francis! https://tiacloud.io/

** Project goal
After a chat with Guille it is clear that XF DevOps team is dealing with some friction when hiring new colleages.

A practical test is required to check kubernetes capabilities of new candidates.

The goal is to create an environment that can benefit from GCP Runner capabilities so:
- labs are scalable
- labs are isolated
- labs can be created on demand
- labs can be done in parallel

** Replace Azure with GCP
The repo started using Azure. On XF we use GCP. Some changes are required to use GCP Runner instead of Azure.

** Coder based project
As per README docs the base image used for Docker is defined in https://github.com/coder/code-server/tree/main/ci/release-image

Surely tiacloudinfo Container Registry in Docker Hub needs to be replicated with XF resources.

** Partial automation in place
There is `create_lab.sh` and `delete_lab.sh` in place to automate labs management. These are the scripts that need update be used with GCP instead of Azure.
